= Battle Fatigue
:hp-tags: Imposter Syndrome, Self Confidence, Procrastination

I've been working with ThoughtWorks for just over 6 weeks now as a "Senior Infrasturucture Developer" or "DevOps Consultant".

As a lateral hire straight from industry, I had a 2 day induction, spent 3 days on "The Beach" in the Manchester office and  got dropped in at the deep end on a Local Government delivery and digital transformation project.

It hasn't been easy and coming from a place where I knew exactly where my boundaries were, set my own experience and had overall freedom to a consultancy position with a local government client hasn't been easy.

== Imposter Syndrome

Almost every day I battle Imposter Syndrome which I'm realising is quite a common ThoughtWorker trait. We're working in an industry that is filled with great people, many of them working alongside us.

I think the nature of the tech industry itself generates a lot of anxiety in those in it. Especially us generalists who feel like we should (and want to) know everything. There's so many new things going on, new opinions, new products and new key notes / presentations popping up on youtube.

These all create the perfect environment for anxiety, procrastination and imposter syndrome to grow, sometimes uncontrollably. 

I'd like to take the opportunity to bring some reality to all of us who feel inadequate or like we should be as awesome as the speakers we admire. 

Here's a perfect video to demonstrate (watch the whole thing):

https://www.destroyallsoftware.com/talks/a-whole-new-world[*Destroy All Software - A whole New World.*]

Wow! What an awesome and believable presentation. If you're like me, you were probably frantically searching Github for this amazing text editor until he admitted: *It was all a lie!* 

I'm not saying everyone who gives a cool presentation is lying. Just that what they are showing you is often an opinion, an extension of the truth, a truth which is personal to them.

== Procrastination

I think a key contributor to imposter syndrome and the anxiety that comes with it is procrastination. Everyone procrastinates at times, often we need to research think, investigate others experiences and read documentation on technologies before we decide they are fit for purpose. Then we build things rapidly in quite a small amount of time in comparison to the thinking time. 

Procrastination and thinking time is all very well when you have a deadline. you can make a decision when you've gathered enough info and watched enough cats fall off things, to get on with building something.

Where procrastination becomes a problem is in situations where you have no dead line. situations like life that seem never ending. This gets worse when you have no goal, no vision of your own future. I guess it's a higher form of mindfulness, you're permanently in the moment. This is not an easy place to be (believe me). going with the flow for a long time makes you feel as if you're a spectator or even an intruder in your own life. 

Tim Urban (https://twitter.com/waitbutwhy[*@waitbutwhy*]) has recently done a TED talk on procrastination, which I think is one of the top TED talks I've seen:

video::mMOHfgKxuYI[youtube]

