= Easy Infrastructure Testing with GOSS
:hp-tags: Configuration Management, Testing, Security, Monitoring, goss

In the world of infrastructure new servers, VMs, containers or applications are often manually validated by a human and some form of build document or checkbox exercise takes place. Even with configuration management, mistakes happen and humans miss things.

Wouldn't it be great if there were an easy way to automatically validate new servers before they are live and we find the problems in production? Well, there is!

== What is Goss?
https://github.com/aelsabbahy/goss[Goss] is a tool that let's you easily test and validate infrastructure. Like http://serverspec.org/[Serverspec] but without all the code. Goss allows you to define what a piece of infrastructure should look like with YAML or JSON. This is made even easier for us with the ability to auto add resources to the Goss configuration.

Goss allows you to validate many different resource types such as files, users, groups, packages, services and http connectivity. You can read the full https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#available-tests[Goss documentation].

== Why Goss? 
Well, a few things make goss awesome: 

* Written in Go - it's a self contained binary with no dependencies on other libraries or Ruby. 
* It's super fast - taking advantages of Go's concurrency model tests are executed and returned almost instantly.
* It's easy to get started with - defining resources in YAML or JSON makes it easy for infrastructure teams who may have limited development experience to get to grips with.

== Server Validation and Monitoring



